Various fixes
dlfcn-win32/dlfcn-win32 pull request #95
Opened 2021-02-03 20:25 UTC by pali

This pull request contains various fixes for different MSVC and gcc compilers, different Windows versions and also for different compile environment (WDK, _WIN32_WINNT, ...). With these changes, dlfcn-win32 compiles without issues also in Visual Studio 6.0, also in WDK 6001.18002 and also for Windows 7 (K32EnumProcessModules). Compiled library/executable should have same functionality independently of used compiler and chosen target environment.

2021-02-04 11:28 UTC, traversaro approved these changes
Thanks @pali !

2021-02-04 11:28 UTC, traversaro commented
Not sure if @rhabacker wants to have a look, otherwise I will merge later today.

2021-02-04 12:14 UTC, rhabacker requested changes

2021-02-04 12:14 UTC, rhabacker commented on src/dlfcn.c
> +    HMODULE kernel32;
The variable ` HMODULE kernel32;` is only used in the block starting at line 213 with `if( !failed && GetModuleHandleExAPtr == NULL )` and could be moved to that location.

2021-02-04 12:14 UTC, rhabacker commented on src/dlfcn.c
> +    MEMORY_BASIC_INFORMATION info;
`info` and `sLen` are also only be used in a local block and could be moved to the `else` block starting at line 229.

2021-02-04 19:48 UTC, rhabacker commented on src/dlfcn.c
> +    UINT uMode;
` UINT uMode;` is also used in a local block and can be move to the beginning of that block.

2021-02-04 19:48 UTC, rhabacker commented on src/dlfcn.c
>      HMODULE psapi;
This is the same case as with `uMode`.

2021-02-21 13:12 UTC, pali commented
I do not think that above changes have any benefit. Declaration of unused variable does not change anything.

The only difference in my second commit is the fact that it avoids calling GetCurrentProcess() function when not needed.

2021-02-24 08:54 UTC, traversaro commented
Thanks @rhabacker for the comments and @pali for the PR. As @pali mentioned, declaring variable just when they are used is something that make sense in some cases, but not something that is documented that we are enforcing in a strict way. I think we can merge the PR as it is and if someone wants to improve the code style, is welcome to submit a PR, thanks!

2021-02-24 08:54 UTC, merged